const timestamp = new Date().toISOString().replace("T", " ").replace("Z", "");
export const browserstackIosCaps = {
  platformName: "iOS",
  "appium:deviceName": "iPhone 15 Plus",
  "appium:automationName": "XCUITest",
  "appium:app": "bs://290b5edb7a9799a60fb68d939f2fe8b0861ed185",
  "appium:xcodeSigningId": "iPhone Developer",
  "appium:useNewWDA": true,
  "appium:showXcodeLog": true,
  "appium:wdaStartupRetries": 3,
  "appium:autoGrantPermissions": true,
  "appium:autoAcceptAlerts": true,
  "appium:fullReset": true,
  "appium:noReset": false,
  "bstack:options": {
    projectName: "SQUADI Mobile App Automation",
    buildName: `SQUADI Automation iOS TESTS ${timestamp}`,
    sessionName: "iOS Test Session",
    debug: true,
    networkLogs: true,
    video: true,
    appiumLogs: true,
    deviceLogs: true,
    local: false,
  },
};
