const timestamp = new Date().toISOString().replace("T", " ").replace("Z", "");
export const browserstackAndroidCaps = {
  platformName: "Android",
  "appium:platformVersion": "14.0",
  "appium:deviceName": "Google Pixel 8 Pro",
  "appium:automationName": "UiAutomator2",
  "appium:app": "bs://40e820f9f7baa012fd9b49127042221acd45c4b6",
  "appium:autoGrantPermissions": true,
  "appium:autoAcceptAlerts": true,
  "appium:disableHiddenApiPolicyPrePApp": true,
  "appium:ignoreHiddenApiPolicyError": true,
  "appium:newCommandTimeout": 300,
  "appium:connectHardwareKeyboard": true,
  "bstack:options": {
    projectName: "SQUADI Mobile App Automation",
    buildName: `SQUADI Automation Android TESTS ${timestamp}`,
    sessionName: "Android Test Session",
    debug: true,
    networkLogs: true,
    video: true,
    appiumLogs: true,
    deviceLogs: true,
    local: false,
  },
  "appium:fullReset": true,
  "appium:noReset": false,
};
